#!/bin/bash

# React UI Manual Test Checklist
# Run this after starting: npm run dev (in frontend directory)

echo "🧪 React UI Test Checklist"
echo "=========================="
echo ""
echo "✅ Prerequisites:"
echo "   1. React dev server running: http://localhost:5173"
echo "   2. Backend services running (optional for UI testing)"
echo ""
echo "📋 Manual Tests:"
echo ""
echo "1. Homepage & Navigation"
echo "   □ Open http://localhost:5173"
echo "   □ Header shows 'Neural Vault'"
echo "   □ See 7 tabs: Chat, Documents, Settings, Metrics, Lab Guide, Q&A, Feedback"
echo "   □ Stats in header (Model, Chunks, Documents, Graph Nodes)"
echo ""
echo "2. Chat Tab"
echo "   □ Click 'Chat' tab"
echo "   □ See empty state or message input"
echo "   □ Input bar visible at bottom"
echo "   □ Suggested queries shown"
echo ""
echo "3. Documents Tab"
echo "   □ Click 'Documents' tab"
echo "   □ See upload area with drag & drop"
echo "   □ File type restrictions mentioned"
echo "   □ Document list (if any uploaded)"
echo ""
echo "4. Settings Tab"
echo "   □ Click 'Settings' tab"
echo "   □ See Model selector"
echo "   □ See RAG feature toggles (Query Expansion, BM25, Hybrid, etc.)"
echo "   □ See sliders (Temperature, Top-K, Context Window)"
echo "   □ See Quick Presets section"
echo "   □ See Metadata Filters section"
echo ""
echo "5. Metrics Tab"
echo "   □ Click 'Metrics' tab"
echo "   □ See summary cards (Total Queries, Avg Latency, etc.)"
echo "   □ See 'Export CSV' and 'Clear' buttons"
echo "   □ See query history or empty state"
echo ""
echo "6. Lab Guide Tab"
echo "   □ Click 'Lab Guide' tab"
echo "   □ See progress tracker"
echo "   □ See collapsible sections (Introduction to RAG, etc.)"
echo "   □ Sections expand/collapse on click"
echo ""
echo "7. Q&A Tab"
echo "   □ Click 'Q&A' tab"
echo "   □ See FAQ categories"
echo "   □ Questions expand/collapse"
echo ""
echo "8. Feedback Tab"
echo "   □ Click 'Feedback' tab"
echo "   □ See star rating (1-5)"
echo "   □ See category buttons"
echo "   □ See comment textarea"
echo "   □ See submit button"
echo ""
echo "9. Responsive Design"
echo "   □ Resize browser window"
echo "   □ UI adapts to different sizes"
echo "   □ No horizontal scrolling issues"
echo ""
echo "10. Styling & Polish"
echo "   □ Dark theme applied correctly"
echo "   □ Smooth tab transitions"
echo "   □ Hover effects work"
echo "   □ No console errors (F12 -> Console)"
echo ""
echo "🎨 Visual Check:"
echo "   □ Modern, professional appearance"
echo "   □ Good contrast and readability"
echo "   □ Icons and emojis render correctly"
echo "   □ Consistent spacing and alignment"
echo ""
echo "=========================="
echo "✅ All tests passed? React UI is working!"
echo ""

